### ISSUE TITLE
Add a simple binary restart mechanism

### ISSUE THREAD

**Issue by jeff-cohere** [RDycore/RDycore#102]
As a prelude to #41, we are adding a binary-format restart capability to RDycore using [PetscBag](https://petsc.org/release/manualpages/Sys/PetscBag/) and [PetscViewer](https://petsc.org/release/manualpages/Viewer/PetscViewer/).

@bishtgautam has pointed to examples in PFlotran to help us get started, including
* [a struct that stores simulation metadata](https://bitbucket.org/pflotran/pflotran/src/f0fe931c72c03580e489724afeb8c5451406b942/src/pflotran/timestepper_base.F90#lines-91) and [its registration in a PetscBag](https://bitbucket.org/pflotran/pflotran/src/f0fe931c72c03580e489724afeb8c5451406b942/src/pflotran/timestepper_base.F90#lines-934)
* [the dumping of solution data using a PetscViewer](https://bitbucket.org/pflotran/pflotran/src/f0fe931c72c03580e489724afeb8c5451406b942/src/pflotran/checkpoint.F90#lines-365)

## Design Questions

This list probably isn't complete.

1. What data and metadata are required for a complete restart of a simulation? Consider that we might want to allow restarts on different numbers of processes.
2. How does a user indicate that a simulation should be loaded from a restart instead of initialized? For example, do they simply add a `-restart` flag on the command line that indicates either a specific file or "the latest in a sequence"?
3. What exactly is the restart process? Do we go through the ordinary initialization process (loading the mesh, setting up Sections, etc) and then load solution and auxiliary data from the restart file?

**Comment by bishtgautam** [comment]
1. Regarding metadata:
   - Save the number of MPI tasks
   - Save TS settings (e.g. type, current time)
   - Save info regarding the solver (i.e. PETSc or CEED+CPU or CEED+GPU)
   - Output file counter for file name
 2. We should introduce a `restart` block in the yaml that could use some of the similar information that is in E3SM XML files:
    - `REST_N` to describes the frequency of restart file
    - `REST_OPTION` that defines the time units (e.g., nsteps, ndays, etc)
    - If `CONTINUE_RUN` is TRUE, then the model reads the  `*.elm.r.*.nc`
ELM will by default write out the `rpointer.lnd`, an ASCII file, that contains the name of the latest ELM restart file, which is named `*.elm.r.*.nc`.
3. Yes, go through the ordinary procedure of model initialization with some checks (e.g. can't change TS settings, switch solver type) and then load and scatter solution Vector. 
 
Ideally, we don't want to allow the number of MPI tasks to change in a "restart" run, because that will be non-BFB for even an explicit time integration scheme as the order of operations would change. We could add a flag in the `restart` block to allow the expert user to change number of MPI tasks in a restart run.

**Comment by jedbrown** [comment]
We could look to ceed-fluids and ratel for an example (we use `-continue_filename checkpoint.bin`, as a PETSc binary file with metadata before the solution state). It does not support changing the number of processes -- we intend to support that with CGNS, but it requires a mesh file (not generating on the fly) since you need to know how to interpret the solution checkpoint. With CGNS, those are already connected. We'll be implementing this in PETSc so it'll just be available. I would not recommend writing scatters directly in rdycore.

There are reasons to change TS and solver settings on a restart. The restart can set the initial time step, but shouldn't prevent further changes.
