### ISSUE TITLE
Improve RDyGetTime()

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#160]
`RDyGetTime(rdy, &time)` returns `time` in the units time is specified in the yaml file, but this is not very obvious. 

Here are two suggestions to improve:
- Replace `RDyGetTime` with `RDyGetTimeInSeconds()`, `RDyGetTimeInMinutes()`, etc, or
- Extend to accept another argument related to time units `RDyGetTime(rdy, 'seconds', &time)`

**Comment by jedbrown** [comment]
Is it always the case that the call site knows what units it wants, or might that be chosen by the user (presumably seconds, minutes, hours, days, perhaps years)? One can either have `struct TimeUnit { double unit_in_seconds; }` or an enum with the possible values. The `TimeUnit` could contain a field with its human-readable name. Any output should include the unit name so that it's unambiguous.
