### ISSUE TITLE
Add new capabilities in RDycore to improve ELM-RDycore integration

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#58]
Modify https://github.com/RDycore/RDycore/blob/main/driver/main.F90#L34-L39

```
      ! create rdycore and set it up with the given file
      PetscCallA(RDyCreate(PETSC_COMM_WORLD, config_file, rdy_, ierr))
      PetscCallA(RDySetup(rdy_, ierr))
      PetscCallA(RDyGetNumLocalCells(rdy_, ncells, ierr))

      allocate(h(ncells))
      allocate(u(ncells))
      allocate(v(ncells))

      integration_time_step = 60.d0 * 3.d0 ! 3 hr
      next_integration_time_step = 0.d0

      ! Run the simulation to completion.
      do istep = 1, nstep

        next_integration_time_step = next_integration_time_step + integration_time_step

        ! To get started, there is no data sent to RDycore because the 
        ! source/sink term is missing in RDycore physics

        ! Run RDycore forward for till the next integration time step
        PetscCallA(RDyRunToTime(rdy_, next_integration_time_step, ierr))

        ! Extract data from RDycore
        PetscCallA(RDyGetHeight(rdy_, h, ierr)
        PetscCallA(RDyGetXVelocity(rdy_, u, ierr)
        PetscCallA(RDyGetYVelocity(rdy_, v, ierr)
      enddo

      ! destroy it
      PetscCallA(RDyDestroy(rdy_, ierr));
```

**Comment by jeff-cohere** [comment]
@jedbrown , as you can see above, we would like to be able to tell TS to "take a single step" instead of running start-to-finish. In other words, I think ELM wants to be able to drive the simulation, so I'm considering adding an `RDyStep` method that takes a single time step of the requested size.

I'm sure you've encountered this scenario in the context of TS, and I know there are issues to consider in how we do this (for example, overshooting requested times and back-interpolating, preserving and/or resetting time integrator states, etc). I see also that PETSc discourages calling `TSStep`directly, probably for all these reasons.

Can you make any recommendations about how best to support the ability for a client application to request that RDycore advance its state by a "single time step" (irrespective of that actual number of underlying steps)?  Should we use `TSSolve` and be prepared to reset the integrator's state for each of our requested time steps, or handle the integrator's state manually in tandem with a call to `TSStep`, or...?

**Comment by jedbrown** [comment]
It depends if we're subcycling or literally just taking one step (perhaps with a multistage method). There's nothing wrong with calling `TSStep` directly, but it means you're responsible for monitoring and step size control as applicable. The code in `TSSolve` is relatively straightforward and you can copy any relevant parts into this driver.

However, the need appears to be more like "advance the state by three hours", which fits the `TSSolve` model. You can use `TS_EXACTFINALTIME_MATCHSTEP` if needed. I suspect adaptive time stepping will be used, but if we're doing constant time steps, you could calculate the step size so you hit the final time accurately. Note that this splitting reduces the coupled time integrator to first order accuracy (but other components are much worse than first order).

![image](https://github.com/RDycore/RDycore/assets/3303/7d378c32-9a17-49d6-b0bd-f94e64940418)
