### ISSUE TITLE
Create an example for TSSetCFLTimeLocal in PETSc

### ISSUE THREAD

**Issue by bishtgautam** [RDycore/RDycore#80]

**Comment by jeff-cohere** [comment]
Hey @jedbrown ,

@bishtgautam and I have been looking more closely at this, and it seems to us that adaptive timestepping would require us to communicate a maximum wave speed for the CFL condition between the host and device each time step for CEED-powered simulations. We concluded this because one has to set the TS timestep on the host, and we only have the wave speeds on the device.

Is this correct? If so, is there any way to get around this transfer (in principle if not practice)? How do other accelerator-sensible applications handle this situation using TS?

**Comment by knepley** [comment]
I guess we should have this for comparison, but according to the KAUST people, using CFL for timestepping is outdated, and we should instead be using the DSP timestepper, properly calibrated.

**Comment by jedbrown** [comment]
That is true of any adaptive time stepping, and usually done using `CeedOperatorSetContextDouble`. The special thing that CFL-based stepping needs is a local CFL estimate that gets reduced to give a global value.

**Comment by bishtgautam** [comment]
We don't need to fix this issue as #210 added adaptive dt.
